### PR TITLE
allow proxy via headers or agent

### PR DESCRIPTION
**Pull request by fembem**
Allow using a proxy, either via specialized HTTP headers or via an http/https agent like `tunnel` or `tunnel-agent`.

### CODE REVIEW

**Comment by xr0master** [comment]
Not sure I understand the idea. If you need a proxy, it's better to set up it before the server.

**Comment by fembem** [comment]
This would be for applications that don't want to send every call via a proxy, that use different proxies for different calls, or where traffic isn't automatically routed via a proxy.

**Comment by xr0master** [comment]
It sounds like a very specific request for your application, why would Mailgan transport users need it?

In addition, this isn't the proxy, but the use of non-Mailgan servers for the requests, I highly doubt that anyone will need it. I suggest you use a real proxy server to distribute your requests. It is not correct to do this in the application. IMO.

**Comment by joedicator** [comment]
This is a common use case in regulated industries where all egress must go through a corporate proxy for monitoring and control.  Some SDKs respect http_proxy/https_proxy env var values, but apparently this one does not.

**Comment by xr0master** [comment]
This sounds unconvincing, all my experience shows that there is no real application for this functionality. This is too specific  request for your unique system, for which I recommend you create your own transport.

Thank you very much for your participation.

**Pull request closed without merging**
